<div class="vspace"></div>
<div class="row">
    <div class="col s12 m6 offset-m3" >
        <div class="row">
            <div class="card waves-block">
                <div class="card-title  black-text">
                    <?php if($this->url== null): ?>
                        <div class="center">Error Happened!!</div>
                    <?php else: ?>
                        <div class="center">Your URL!</div>
                    <?php endif;?>
                </div>
                <div class="card-content">
                    <div class="row center">
                        <div class="s12">
                            <?php if ($this->error!=null) : ?>
                                <?=$this->error?>
                            <?php else : ?>
                                <?=$this->url?>
                            <?php endif;?>
                        </div>
                        <div class="input-field s12"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>