<div class="vspace"></div>
<div class="row">
    <div class="col s12 m6 offset-m3" >
        <div class="row">
            <div class="card waves-block">
                <div class="card-title  black-text">
                    <div class="center">Your URL!</div>
                </div>
                <div class="card-content">
                    <div class="row center">
                        <div class="s12">
                            <?=$this->url?>
                        </div>
                        <div class="input-field s12"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>