<?php echo $this->doctype(); ?>

<html>
<head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/css/site.css"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <?php $this->headScript()->prependFile('/js/jquery-2.1.1.min.js','text/javascript')  ?>
    <?php $this->headScript()->appendFile('/js/materialize.min.js','text/javascript')  ?>
    <?php echo $this->headScript() ?>

</head>

<body class="grey lighten-4">
<nav>
    <div class="nav-wrapper white">
        <a href="/" class="brand-logo grey-text darken-3 logo-text">Less Characters!</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a class="grey-text darken-3" href="/url/try">Short it!</a></li>
            <li><a class="grey-text darken-3" href="/url/track">Track it!</a></li>
        </ul>
    </div>
</nav>
<div class="container">
<?=$this->content; ?>
</div>
</body>
</html>