<div class="section">
    <div class="container center grey-text darken-3">
        <h1 class="">Your Url Shortener!</h1>
        <div class="row center">
            <h5>Free service, no need to sign up! unless you want to track your links</h5>
        </div>
        <div class="row center">
            <a href="/short" id="download-button" class="btn-large waves-effect waves-light grey">Get Started</a>
        </div>
    </div>
</div>